### PR TITLE
Implement support for custom aggregators (closes #76)

### LINKED ISSUE #76: Allow custom Aggregators/Calculators
I'd like to be able to register my own calculators with your framework.  You can see how I'm doing it below.  It would be nice if this was incorporated into your library - you can make the changes or allow me to commit.
In DevExtreme.AspNet.Data.Aggregation.AggregateCalculator:

```
        private static Dictionary<String, Type> customCalculators = new Dictionary<string, Type>();

        public static void registerCustomCalc(String name, Type type)
        {
            customCalculators[name] = type;
        }

        Aggregator<T> CreateAggregator(string summaryType)
        {
            /* existing calculators */

            Type type;
            if (customCalculators.TryGetValue(summaryType, out type))
                return Activator.CreateInstance(type, _accessor) as Aggregator<T>;

            throw new NotSupportedException();
        }
```

Usage in my service:

```
DevExtreme.AspNet.Data.Aggregation.AggregateCalculator<PositionModel>.registerCustomCalc("countLS", typeof(CountLSAggregator<PositionModel>));
```

Then in dxDataGrid:

```
totalItems: [
                    {
                        column: "Quantity",
                        summaryType: "countLS",
                        alignByColumn: true
                    },
                    . . . 
```

### PR DESCRIPTION
**Pull request by olegbevz**
Hello,

According to ticket #T607192 I've added support for custom aggregators in DevExtreme.AspNet.Data.
AggregatorRegistry class is responsible to store creation functions for custom and default aggregators.
I've also implemented tests for new functionality.

Ticket: https://www.devexpress.com/Support/Center/Question/Details/T607192/support-custom-aggregators-in-devextreme-aspnet-data

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@olegbevz 

Thanks for your contribution.

I don't like adding static `_aggregatorRegistry` to the generic `AggregateCalculator<T>` for the reasons described in https://stackoverflow.com/a/9665168

Instead I'd suggest to introduce a separate registry holding parameterless types of custom aggregators. Draft:

```c#
public static class CustomAggregators {
    static readonly Dictionary<string, Type> _registry;

    public static void Register(string summaryType, Type aggregatorType) {
    }

    public static Aggregator<T> Instantiate<T>(string summaryType, IAccessor<T> accessor) {
        return (Aggregator<T>)Activator.CreateInstance(
            _registry[summaryType].MakeGenericType(typeof(T)),
            accessor
        );
    }
}
```

Usage:
```c#
Aggregation.CustomAggregators.Register("comma", typeof(CommaAggregator<>));
```

What do you think?

Other notes:
- Don't express built-in summaries via custom aggregators.
- Don't make unnecessary diffs such as [edits of existing usings](https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/205/files#diff-8b29bfd47fe01d1e9712c97f570c8fe7L4), [changing style of existing code](https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/205/files#diff-5ef661036a9141ad0efba3205f0a3d28R31).
GitHub [compare view](https://help.github.com/articles/comparing-commits-across-time/) helps to ensure that the changeset is clean.

Related: #76

**Comment by olegbevz** [comment]
@AlekseyMartynov , totally agree with you: it's not the best way to register aggregator for each object type.
I see no reason why not to use the same approach for creating built-in and custom aggregators, but, yes, I can return switch/case statement.

**Comment by AlekseyMartynov** [comment]
> I see no reason why not to use the same approach for creating built-in and custom aggregators

Maybe we'll combine them later. However now when there's no complete picture of custom summaries, let's focus on adding new code. Handling the different number of built-in aggregators' constructor arguments and creating them via `Activator` can possibly complicate the code rather then simplify it.

**Comment by AlekseyMartynov** [comment]
I suggest some edits: https://github.com/olegbevz/DevExtreme.AspNet.Data/pull/1
Commit messages should give context.

**Comment by AlekseyMartynov** [comment]
@San4es any notes?

**Pull request merged**
