### PR TITLE
Support up to 256 group summaries in DevExtreme.AspNet.Data

### PR DESCRIPTION
**Pull request by badcodelab**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
> Currently we unable to switch on the remote group paging option for it and browser loads 40-50 MB of data for Grid.

I mean this option:
https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/d791d593f88a9fafc46aeb976991be60955ca547/net/DevExtreme.AspNet.Data/DataSourceLoadOptionsBase.cs#L76-L79

It doesn't mean grouping in browser. If it's set to `false`, grouping is not translated to LINQ but is still evaluated on server. Have you tried it?

@RomanTsukanov we better change "server side" to "LINQ" in `<summary>`

**Comment by AlekseyMartynov** [comment]
**UPDATE**
From https://devexpress.com/issue=T608049 I see that you work with `ExpandoObjects`.
For in-memory data `RemoteGrouping` doesn't make sense. What is the reason for forcing `RemoteGrouping` to `true`?

**Comment by badcodelab** [comment]
@AlekseyMartynov we used to work with `ExpandoObjects` but moved to `dynamic` models.
Please check out this DevTools [screenshot](https://www.dropbox.com/s/ocm1gns9unyxz73/groupPaging.png?dl=0) from Network tab.
The first request is sent from DataGrid component using DataSource object configured with the following: 
``
<dxo-remote-operations [paging]="true" [sorting]="true" [filtering]="true" [summary]="true" [grouping]="true" [groupPaging]="false"></dxo-remote-operations>
``
If we change angular input `[groupPaging]` to `true` DataSource splits this request onto 2 much smaller ones.
But in our case it requires the proposed changes.
Another solution which suits us as well is to make MAX_SIZE configurable.

**Comment by AlekseyMartynov** [comment]
> If we change angular input `[groupPaging`] to `true` DataSource splits this request onto 2 much smaller ones.

It's clear, and it's the [purpose of the `groupPaging` option](https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Enhance_Performance_on_Large_Datasets/#Remote_Group_Paging).

However, `loadOptions.RemoteGrouping` is different and unrelated.
Set `RemoteGrouping=false` in C# code and `groupPaging=true` in grid configuration.
Does it work?

Typically you don't need to modify `loadOptions.RemoteGrouping`. It should default to `false` for `dynamic` data. If you set it to `true` for a reason, then please tell us why. We might need more context to fully understand the scenario.

**Comment by badcodelab** [comment]
Looks strange but it works. The only difference I see is in sort order.
Do you have any idea why that happens?

**Comment by AlekseyMartynov** [comment]
> The only difference I see is in sort order.
Do you have any idea why that happens?

Can you share an example of that difference?
What version of DevExtreme do you use?

**Comment by AlekseyMartynov** [comment]
@badcodelab
We now have an experimental branch in which nested `Tuples` are used instead of `AnonType`:
https://github.com/DevExpress/DevExtreme.AspNet.Data/compare/master...AlekseyMartynov:tuples

I'd appreciate if you test it with a lot of summary items in your project.
Pre-built packages:
https://ci.appveyor.com/project/AlekseyMartynov/devextreme-aspnet-data/build/artifacts?branch=tuples

**Pull request closed without merging**
