### PR TITLE
Fix filter expression compilation by enum-typed field (Resolves #73)

### LINKED ISSUE #73: The DataSourceLoader.Load method - Filtering does not work correctly with enum typed fields
The `DataSourceLoader.Load` method returns an empty result with enum typed fields.

Debugging a user's sample project in the [T412494](https://www.devexpress.com/Support/Center/Question/Details/T412494) ticket, I reproduced this issue with the simple code below:

```c#
using System;
using System.Collections.Generic;
using DevExtreme.AspNet.Data;
using Newtonsoft.Json;

namespace EnumField {

    class Program {
        public enum OrderType { One, Two }

        class Order {
            public Enum OrderType { get; set; }
        }

        public partial class DataSourceLoadOptions : DataSourceLoadOptionsBase { }

        static void Main(string[] args) {

            var orders = new List<Order>() {
                new Order { OrderType = OrderType.One },
                new Order { OrderType = OrderType.Two }
            };

            var loadOptions = new DataSourceLoadOptions() {
                Filter = new List<object>(new object[] { "OrderType", "=", 1 })
            };

            var result = DataSourceLoader.Load(orders, loadOptions);
            Console.WriteLine(JsonConvert.SerializeObject(result));
        }
    }
}
```

### PR DESCRIPTION
**Pull request by San4es**
/cc @AlekseyMartynov

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
LGTM

**Comment by nikschuiling** [comment]
Hi, when will a new version that includes this fix be released?

**Comment by San4es** [comment]
Hi @nikschuiling 

We have AppVeyor build artifacts [here](https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/build/172/artifacts). They include this fix. Please try them.

**Comment by nikschuiling** [comment]
@San4es tnx, fix confirmed.

**Comment by San4es** [comment]
@nikschuiling thank you, too!

**Pull request merged**
