### PR TITLE
Ugly workaround for issue T410383.

### PR DESCRIPTION
**Pull request by jtheisen**
See ticket [T410383](https://www.devexpress.com/Support/Center/Question/Details/T410383).

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Hi @jtheisen 

Could you please check if rewriting the query as suggested in http://stackoverflow.com/a/23558389 helps?

```
from e in db.MyEntities
from o in db.MyOtherEntities.Where(o => o.Foo == e.Foo).DefaultIfEmpty()
select new {
    Value1 = e.Value1,
    Value2 = e.Value2
};
```

**Comment by jtheisen** [comment]
Yes, it does.

I just figured what also helps if there's a spurious where clause after the join, such as

    where e.Value1 == e.Value1

Just writing `where true` is not enough though.

Very mysterious.

Ok, now that there's a (less ugly) workaround there's no point in the pull request.

I wrote this SO Q/A: http://stackoverflow.com/questions/38743577/the-nested-query-is-not-supported-entity-framework-fails-on-grouped-left-joins

And maybe there should be a bug report to EF - I won't be the last tripping over this.

If you want to be really nice to your users, you *could* catch the `NotSupportedException` and rethrow with a piece of info attached with a link to this or SO in case that's the issue.

**Comment by jtheisen** [comment]
Tried to file a bug an connect.microsoft.com but failed. The site's too buggy itself.

**Comment by AlekseyMartynov** [comment]
> Tried to file a bug an connect.microsoft.com but failed.

Good news, EF6 is now on GitHub: https://github.com/aspnet/EntityFramework6

> If you want to be really nice to your users, you could catch the NotSupportedException and rethrow with a piece of info attached with a link to this or SO in case that's the issue.

That's a good idea. We'll keep it in mind.
Thanks.

**Pull request closed without merging**
