### PR TITLE
Implemented CustomSortCompilers

### PR DESCRIPTION
**Pull request by zVolodymyr**
Adding ability to create custom sort expressions

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Hello

Thanks for your input.

Have you considered alternative approaches? For example, you can add an additional `Priority` property. Whenever sorting by `Name` is requested, you can insert a pre-sort by `Priority` as shown below:

```c#
var loadOptions = new DataSourceLoadOptionsBase
{
    Sort = new[] {
        new SortingInfo { Selector = "Name", Desc = false }
    }
};

// your controller starts

var nameSorting = loadOptions.Sort?.FirstOrDefault(i => i.Selector == "Name");
if (nameSorting != null)
{
    var newSorting = new List<SortingInfo>(loadOptions.Sort);
    newSorting.Insert(0, new SortingInfo { Selector = "Priority", Desc = !nameSorting.Desc });
    loadOptions.Sort = newSorting.ToArray();
}
```

I think it is easier that dealing with LINQ expressions trees.

**Comment by zVolodymyr** [comment]
Actually I use that approach in my current project. But it has one drawback - it requires adding of additional properties to models (like "Priority")

**Comment by AlekseyMartynov** [comment]
No problem. The property can be a custom accessor:

```c#
DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.Register((expr, accessorText) => {
    if (expr.Type == typeof(Product) && accessorText == "Priority") {
        return Expression.Condition(
            Expression.Equal(
                Expression.PropertyOrField(expr, "Name"),
                Expression.Constant("Lightsaber")
            ),
            Expression.Constant(2),
            Expression.Constant(1)
        );
    }
    return null;
});

```

**Comment by zVolodymyr** [comment]
Yeah, it is good idea. Unfortunately I found another big disadvantage of this approach - it doesn't work well with grouping. 
In my current application I was needed to re-sort groups from LoadResult to achieve required sorting order.

**Comment by AlekseyMartynov** [comment]
Indeed, `RemoteGroupExpressionCompiler` [adds `OrderBy`](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/ecb3c83fc1f7aa4b444ae8fba0d8f4f7763189cf/net/DevExtreme.AspNet.Data/RemoteGrouping/RemoteGroupExpressionCompiler.cs#L57-L71) on its own.

Consider another idea then:

```c#
DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.Register((expr, accessorText) => {
    if(String.Equals(accessorText, "ShipCountry", StringComparison.InvariantCultureIgnoreCase)) {
        var concatMethod = typeof(String).GetMethod("Concat", new[] { typeof(String), typeof(String) });
        var propValue = Expression.PropertyOrField(expr, "ShipCountry");
        return Expression.Condition(
            Expression.Equal(
                propValue,
                Expression.Constant("USA")
            ),
            Expression.Call(concatMethod, Expression.Constant("0 "), propValue),
            Expression.Call(concatMethod, Expression.Constant("1 "), propValue)
        );
    }
    return null;
});
```

SQL:
```sql
exec sp_executesql N'SELECT TOP(@__p_0) ...
FROM [Orders] AS [o]
ORDER BY CASE
    WHEN [o].[ShipCountry] = N''USA'' THEN N''0 '' + [o].[ShipCountry]
    ELSE N''1 '' + [o].[ShipCountry]
END, [o].[OrderID]',N'@__p_0 int',@__p_0=20
```

You might need to make this a custom accessor, too, and rewrite the property name only in `Sort` and `Group` parts of the load options, so that the change does not affect filter and display text.

**Comment by zVolodymyr** [comment]
Your last solution doesn't look good. Instead of having one place where we can define new sorting logic, it requires changes in three places - 1) create new accessor, 2) modify input sorting order by adding new field, 3) remove additional characters from group key that will be used on UI

**Comment by AlekseyMartynov** [comment]
I apologize for the misunderstanding. I decided that the suggested solution worked well because you didn't leave any comments since my last reply. Please clarify whether or not the approach actually works and allows you to implement the logic required by your app.

Also, please let me know if you plan to continue working on this pull request. In https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/455#issuecomment-722377337, you correctly noticed that `SortExpressionCompiler` has no effect on grouping, so we cannot merge the patch in its current form.

**Pull request closed without merging**
