### PR TITLE
Describe the configuration of the client side on Angular (resolves #187)

### LINKED ISSUE #187: Update README when nojquery npm is published
- [ ] short description & code sample
- [x] badge

### PR DESCRIPTION
**Pull request by RomanTsukanov**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@nightskylark 
Does the [Angular sample](https://github.com/RomanTsukanov/DevExtreme.AspNet.Data/blob/5dba735b2bd24c61b06e14e12d76ca9f81cb0934/docs/client-side-without-jquery.md#api-reference-and-usage) look good?

**Comment by nightskylark** [comment]
@AlekseyMartynov Looks good. Maybe it would be better to remove `styleUrls` to make an example purer.

**Comment by nightskylark** [comment]
Oh, and I found two missed semicolons.

**Comment by RomanTsukanov** [comment]
I think I see more than two. Just a moment.

**Pull request merged**
