### PR TITLE
store options with which is DataStore created

### PR DESCRIPTION
**Pull request by miroslav-peterka**
It is because I need to read loadParams, from it to call other api with same params

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Alternatively, you can assign them externally, and only those parts that are needed:

```js
function createStore2(options) {
    var store = AspNet.createStore(options);
    store._loadParams = options.loadParams;            
    return store;
}
```

**Comment by miroslav-peterka** [comment]
It will be some problem to have it there all? just for case?

**Comment by AlekseyMartynov** [comment]
Appending them to the resulting `Store` object will mean duplication of data. Options are already there in an intermediate form:
  
 https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/9de39ac3b2cb332c4f98ebc8d141ed9e51030d68/js/dx.aspnet.data.js#L36-L43

Since your use case is sharing `loadParams` between different APIs, a more clean solution is to introduce a sort of API context object like this:

```js
var apis = {
  loadParams: ...,
  store: ...,
  // any extras
}
```

and use it across the app code.

**Comment by miroslav-peterka** [comment]
I understood, but this approach is not possible in our case. If it is problem to store whole options, it will be enough to store just a `store._loadParams = options.loadParams; ` as you recommend.

**Comment by miroslav-peterka** [comment]
I have to admit, I did not fully understood, how you meant it with the wrapper function. I do not want to create own unique DataStore . Inline javascript code is generated on server side by C#. And is not so easy to modify it. Thats why I want to add possibility to read options from that datastore on user action. In our application we are going to used it for export large datagrid to PDF. To do it, I need to get from datagrid its actual state and its datastorage loading params. To generate PDF, I need to send the params to another API.

So if your "wrapper function" is meant to modify file js/dx.aspnet.data.js like this:
```javascript
     function createStore(options) {
         var store = new CustomStore(createStoreConfig(options));
         store._useDefaultSearch = true;
         store._loadParams = options.loadParams;
         return store;
     }
```
It will be OK for my current needs too.

**Comment by San4es** [comment]
>Inline javascript code is generated on server side by C# 

@miroslav-peterka Do we understand it correctly that you are using the DevExtreme MVC Controls?

**Comment by AlekseyMartynov** [comment]
>   if your "wrapper function" is meant to modify file js/dx.aspnet.data.js 

No, on the contrary, my point is that to meet your requirements, no changes are necessary in DevExtreme.AspNet.Data.

In a certain place of your app you definitely have a JavaScript call like this:

```js
DevExtreme.data.AspNet.createStore(...)
```

(or something similar, depending on how dx.aspnet.data.js is loaded and whether or not you are using ES modules)

I suggest a very straightforward thing. Declare *your own* JavaScript function similar to the one from https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/245#issuecomment-389456790 and call it instead of the original `...createStore`. 

To reiterate, from my undetstanding, the changes are needed in the app code, not in the library.

**Comment by miroslav-peterka** [comment]
@San4es yes

server side code looks like
```c#
@(Html.DevExtreme().DataGrid()
...
   .DataSource(d => d.WebApi().ApiController($"{GridKeyList}").Key("Id")
   .LoadParams(new { status = Model.MyData.Status }))
```

@AlekseyMartynov It is possible to keep current server side code (it is used on many pages), together with using own datastorage?

**Comment by AlekseyMartynov** [comment]
Now I understand that you use DevExtreme MVC data sources.

Here are possible solutions.

1. In Layout, right after `<script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>` add the following script:
```js
<script>
    (function () { 
        var originaCreateStore = DevExpress.data.AspNet.createStore;
        DevExpress.data.AspNet.createStore = function (options) {
            var store = originaCreateStore(options);
            store.myLoadParams = options.loadParams;
            return store;
        };
    })();
</script>
```
 
2. Serialize the object used in `LoadParams` as a page-global variable and use it for calling other APIs:
```html
<script>
    var gridDataSourceStatus = @Newtonsoft.Json.JsonConvert.SerializeObject(Model.MyData.Status);
</script>
```

3. Take full manual control over data source instantiation with the `new JS()` helper:

```html
<script>
    function createMyStore() { 
        var store = DevExpress.data.AspNet.createStore({
            key: "Id",
            loadUrl: "@Url.Action("...")"
        });
        store.myLoadParams = @Newtonsoft.Json.JsonConvert.SerializeObject(null/*Model.MyData.Status*/);
        return store;
    }
</script>

@(Html.DevExtreme().DataGrid<Order>()
    .DataSource(new JS("createMyStore()"))
```

I'd suggest to go with the item 2 because it's concise and doesn't introduce unnecessary coupling. Item 1 implements exactly what you do in the PR. Item 3 is the most powerful though less convenient way which you can use in similar cases.

**Pull request closed without merging**
