### PR TITLE
Set _useDefaultSearch flag to make search API work via filtering

### PR DESCRIPTION
**Pull request by AlekseyMartynov**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@San4es please review

@Seteh it would be better if I could set `_useDefaultSearch` via the `CustomStore` constructor. How about adding this capability to the next 15.2.x?

**Comment by San4es** [comment]
@AlekseyMartynov 

    store._useDefaultSearch = true;

this code looks as hack. I agree with you, that we need to provide this option ASAP.

**Comment by San4es** [comment]
@AlekseyMartynov :shipit:

**Comment by Seteh** [comment]
@AlekseyMartynov @San4es `useDefaultSearch` option has been added to the CustomStore configuration and will be available starting with 15.2.10.

**Comment by AlekseyMartynov** [comment]
Great!

**Pull request merged**
